# Generated by Django 5.2.8 on 2025-12-06 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_different_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='product name')),
                ('image', models.ImageField(upload_to='images', verbose_name='upload image')),
                ('descriptions', models.TextField(verbose_name='description')),
                ('price', models.FloatField(verbose_name='price')),
                ('stock', models.IntegerField(verbose_name='stock')),
                ('available', models.BooleanField(default=True, verbose_name='available')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='updated')),
            ],
        ),
    ]
